//
//  ListViewPresenter.swift
//  ToDoList
//
//  Created tambanco 🥳 on 15.03.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol ListViewViewProtocol: AnyObject {
    func setTask(task: String)
}

// MARK: Input protocol
protocol ListViewPresenterProtocol: AnyObject {
    init(view: ListViewViewProtocol, model:  Task)
    func showtask()
}

class ListViewPresenter: ListViewPresenterProtocol {
    

    weak var view: ListViewViewProtocol?
    var model: Task
    
    func showtask() {
        let task = "task"
        self.view?.setTask(task: task)
    }
    
    required init(view: ListViewViewProtocol, model: Task) {
        self.view = view
        self.model = model
    }
}
