//
//  ListViewPresenter.swift
//  ToDoList
//
//  Created tambanco 🥳 on 15.03.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol ListViewViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol ListViewPresenterProtocol: AnyObject {
    init(view: ListViewViewProtocol, model:  ListViewModel)

}

class ListViewPresenter: ListViewPresenterProtocol {

    weak var view: ListViewViewProtocol?
    var model: ListViewModel
    
    // Enter buisness logic here
    
    required init(view: ListViewViewProtocol, model: ListViewModel) {
        self.view = view
        self.model = model
    }
}
