//
//  ListViewPresenter.swift
//  ToDoList
//
//  Created tambanco 🥳 on 15.03.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol ListViewViewProtocol: AnyObject {
    func setList(taskList: [String])
}

// MARK: Input protocol
protocol ListViewPresenterProtocol: AnyObject {
    init(view: ListViewViewProtocol, model:  Task)
    func updateTasks(newTask: String)
}

class ListViewPresenter: ListViewPresenterProtocol {
    
    
    weak var view: ListViewViewProtocol?
    var model: Task
    
    func updateTasks(newTask: String) {
        model.taskList.append(newTask)
        self.view?.setList(taskList: model.taskList)
    }
    
    required init(view: ListViewViewProtocol, model: Task) {
        self.view = view
        self.model = model
    }
}
